plugins {
    id 'java'
    id 'application'
}

group = 'com.javarush'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

application {
    mainClass = 'com.javarush.island.Application'
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
